# Generated by Django 3.2.6 on 2021-08-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210820_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bying_type',
            new_name='buying_type',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Корзина'),
        ),
    ]
